import os
import json
import numpy as np
from typing import Union, Literal, List, Tuple, Any

# Framework imports (generated by FrameworkAdapter)

import torch


from matmul_transeposed_both_torch import Model as FrameworkModel, get_init_inputs, get_inputs

TensorType = torch.Tensor



# DSL imports (generated by DSLAdapter)

import triton

import triton.language as tl


from matmul_transeposed_both_triton_cuda import ModelNew


# Special setup code (e.g., tilelang cache clear, triton patches)


# Binary I/O functions (only for SWFT)


def run_generation_implementations():
    """运行生成实现"""
    # 获取运行模式
    backend = "cuda"  # 计算设备后端
    arch = "a100"  # 硬件架构
    dsl = "triton_cuda"  # 实现方式
    
    # 设备设置 (generated by FrameworkAdapter)

    os.environ['CUDA_VISIBLE_DEVICES'] = str(0)

    device = torch.device("cuda")

    torch.cuda.set_device(0)  # 使用第一个CUDA设备

    
    # 设置随机种子 (generated by FrameworkAdapter)
    
    torch.manual_seed(0)
    

    # 获取初始化参数和输入数据
    init_params = get_init_inputs()
    
    # 设置随机种子以确保framework_model和impl_model的权重一致
    
    torch.manual_seed(0)
    
    
    framework_model = FrameworkModel(*init_params)
    
    
    framework_model = framework_model.to(device)
    
    
    # 创建 impl_model（用于 ModelNew 类格式的 DSL）
    
    impl_model = ModelNew(*init_params)
    
    impl_model = impl_model.to(device)
    
    
    # 输入处理函数 (generated by FrameworkAdapter)

    def process_input(x):

        """处理输入数据，将数据移动到正确的设备"""

        if isinstance(x, torch.Tensor):

            return x.to(device)

        elif isinstance(x, np.ndarray):

            return torch.from_numpy(x).to(device)

        elif isinstance(x, (list, tuple)):

            return type(x)(process_input(item) for item in x)

        elif isinstance(x, (int, float, bool, type(None))):

            return x

        else:

            try:

                return x.to(device)

            except (AttributeError, TypeError):

                return x

    
    def run_benchmark(inputs, case_idx=0):
        """运行基准测试"""

        # 进行最终的性能测试

        def triton_benchmark_fn():

            result = impl_model(*inputs)

            return result

        

        import triton.testing

        execution_time_ms = triton.testing.do_bench(

            triton_benchmark_fn,

            warmup=5,

            rep=50,

            return_mode="median"

        )

        method = "triton_do_bench"


        return execution_time_ms, method
    
    
    # 静态shape：获取单组输入数据
    
    inputs = get_inputs()
    inputs = [process_input(x) for x in inputs]
    
    
    execution_time, method = run_benchmark(inputs, case_idx=0)
    
    # 保存时间结果到文件
    result_data = {
        "execution_time_ms": execution_time,
        "execution_time_us": execution_time * 1000,
        "warmup_times": 5,
        "run_times": 50,
        "method": method,
        "shape_type": "static"
    }
    
    print(f"[matmul_transeposed_both] Generation execution time: {execution_time * 1000:.4f} us")
    
    
    with open("generation_profile_result.json", "w") as f:
        json.dump(result_data, f, indent=2)

if __name__ == "__main__":
    run_generation_implementations()
