import os
import json
import numpy as np
import signal
import functools
from typing import Union, Literal, List, Tuple, Any

# Framework imports (generated by FrameworkAdapter)

import torch


from matmul_transeposed_both_torch import Model as FrameworkModel, get_init_inputs, get_inputs

TensorType = torch.Tensor



# DSL imports (generated by DSLAdapter)

import triton

import triton.language as tl


from matmul_transeposed_both_triton_cuda import ModelNew


# Special setup code (e.g., tilelang cache clear)


# Binary I/O functions (only for SWFT)


# Timeout装饰器函数
def timeout_handler(signum, frame):
    raise TimeoutError("计算超时")

def with_timeout(timeout_seconds):
    """装饰器：为函数添加超时控制"""
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            # 设置信号处理器
            old_handler = signal.signal(signal.SIGALRM, timeout_handler)
            signal.alarm(timeout_seconds)
            try:
                result = func(*args, **kwargs)
                return result
            finally:
                # 恢复原来的信号处理器
                signal.alarm(0)
                signal.signal(signal.SIGALRM, old_handler)
        return wrapper
    return decorator

# Compare functions (generated by FrameworkAdapter)

def get_limit(data_type):

    """Get precision limit for data type"""

    if data_type == torch.float16:

        return 0.004

    elif data_type == torch.bfloat16:

        return 0.03

    elif data_type == torch.int8:

        return 0.01

    else:

        return 0.02



def compare(fw_out, impl_out, limit, data_type):

    """Compare framework output and implementation output using pure PyTorch"""

    # Flatten tensors

    fw_flat = fw_out.flatten().detach().cpu()

    impl_flat = impl_out.flatten()

    if isinstance(impl_flat, torch.Tensor):

        impl_flat = impl_flat.detach().cpu()

    else:

        impl_flat = torch.tensor(impl_flat, dtype=fw_flat.dtype)



    size = fw_flat.numel()



    # 1. 检查形状一致性

    if fw_flat.shape != impl_flat.shape:

        raise AssertionError(f"验证失败，输出形状不一致: framework={fw_flat.shape}, impl={impl_flat.shape}")



    # 2. 检查NaN值

    fw_nan_count = torch.isnan(fw_flat).sum().item()

    impl_nan_count = torch.isnan(impl_flat).sum().item()



    if fw_nan_count > 0 or impl_nan_count > 0:

        raise AssertionError(f"验证失败，检测到NaN值: Framework={fw_nan_count}/{size}, Implementation={impl_nan_count}/{size}")



    # 3. 检查Inf值 - 只有当两边Inf位置和符号都匹配时才允许

    fw_inf_mask = torch.isinf(fw_flat)

    impl_inf_mask = torch.isinf(impl_flat)



    # 检查Inf位置是否匹配

    if not torch.equal(fw_inf_mask, impl_inf_mask):

        fw_inf_count = fw_inf_mask.sum().item()

        impl_inf_count = impl_inf_mask.sum().item()

        raise AssertionError(f"验证失败，Inf位置不匹配: Framework={fw_inf_count}/{size}, Implementation={impl_inf_count}/{size}")



    # 检查Inf符号是否匹配

    if fw_inf_mask.any():

        if not torch.equal(torch.sign(fw_flat[fw_inf_mask]), torch.sign(impl_flat[impl_inf_mask])):

            raise AssertionError(f"验证失败，Inf符号不匹配")



    # 4. 对有限值进行精度比较

    finite_mask = torch.isfinite(fw_flat) & torch.isfinite(impl_flat)

    finite_count = finite_mask.sum().item()



    if finite_count == 0:

        print(f"警告: 所有值都是Inf，跳过精度检查")

        return



    # 提取有限值

    fw_finite = fw_flat[finite_mask]

    impl_finite = impl_flat[finite_mask]



    # 检查是否为布尔类型

    if fw_finite.dtype == torch.bool:

        if not torch.equal(fw_finite, impl_finite):

            raise AssertionError(f"验证失败，布尔值不匹配: dtype={data_type}")

        return



    # 确保数据类型一致（在torch层面转换）

    if impl_finite.dtype != fw_finite.dtype:

        impl_finite = impl_finite.to(fw_finite.dtype)



    # 计算相对误差

    abs_diff = torch.abs(fw_finite.float() - impl_finite.float())

    abs_ref = torch.abs(fw_finite.float())

    eps = 1e-8

    relative_error = torch.where(abs_ref > eps, abs_diff / abs_ref, abs_diff)



    # 统计错误

    err_cnt = (relative_error > limit).sum().item()

    limit_cnt = int(finite_count * limit)



    if err_cnt > limit_cnt:

        max_error = relative_error.max().item()

        mean_error = relative_error.mean().item()



        # 找出不一致的位置

        mismatch_mask = relative_error > limit

        mismatch_indices = torch.where(mismatch_mask)[0]

        # 最多打印10个不一致的位置

        num_to_show = min(10, len(mismatch_indices))



        error_msg = f"验证失败，输出不一致: err_cnt={err_cnt} / {limit_cnt}, dtype={data_type}, limit={limit}\n"

        error_msg += f"最大相对误差: {max_error:.6e}, 平均相对误差: {mean_error:.6e}\n"

        error_msg += f"前 {num_to_show} 个不一致的值:\n"

        for i in range(num_to_show):

            idx = mismatch_indices[i].item()

            error_msg += f"  位置[{idx}]: framework={fw_finite[idx]:.6e}, "

            error_msg += f"impl={impl_finite[idx]:.6e}, "

            error_msg += f"相对误差={relative_error[idx]:.6e}\n"



        raise AssertionError(error_msg)


def verify_implementations():
    """验证框架实现和具体实现的结果一致性"""
    # 获取运行模式
    backend = "cuda"  # 计算设备后端
    arch = "a100"  # 硬件架构
    dsl = "triton_cuda"  # 实现方式
    
    # 设备设置 (generated by FrameworkAdapter)

    os.environ['CUDA_VISIBLE_DEVICES'] = str(0)

    device = torch.device("cuda")

    torch.cuda.set_device(0)  # 使用第一个CUDA设备

    
    # 输入处理函数 (generated by FrameworkAdapter)

    def process_input(x):

        """处理输入数据，将数据移动到正确的设备"""

        if isinstance(x, torch.Tensor):

            return x.to(device)

        elif isinstance(x, np.ndarray):

            return torch.from_numpy(x).to(device)

        elif isinstance(x, (list, tuple)):

            return type(x)(process_input(item) for item in x)

        elif isinstance(x, (int, float, bool, type(None))):

            return x

        else:

            try:

                return x.to(device)

            except (AttributeError, TypeError):

                return x


    def verify_single_case(inputs_for_framework, inputs_for_impl):
        """验证单个案例的公共逻辑"""
        
        
        # 设置随机种子 (generated by FrameworkAdapter)
        
        torch.manual_seed(0)
        

        # 运行实现 (generated by DSLAdapter)
        
        impl_output = impl_model(*inputs_for_impl)
        

        # 运行原始实现
        framework_output = framework_model(*inputs_for_framework)

        if not isinstance(framework_output, (list, tuple)):
            framework_output = [framework_output]
        if not isinstance(impl_output, (list, tuple)):
            impl_output = [impl_output]
        
        # 基本检查
        if len(framework_output) != len(impl_output):
            raise AssertionError(f"验证失败，输出数量不一致: framework={len(framework_output)}, impl={len(impl_output)}")
        
        for i, (fw_out, impl_out) in enumerate(zip(framework_output, impl_output)):
            # 检查None值
            if fw_out is None or impl_out is None:
                raise AssertionError(f"输出{i}为None: framework={fw_out is None}, impl={impl_out is None}")
            
            # 执行比对（compare 函数由 FrameworkAdapter 生成，使用框架原生操作）
            
            data_type = framework_output[i].dtype
            
            limit = get_limit(data_type)
            
            compare(fw_out, impl_out, limit, data_type)
            
        
        return True, framework_output

    def verify_with_timeout(inputs_for_framework, inputs_for_impl, timeout_msg=None, success_msg=None):
        """带超时控制的验证函数"""
        @with_timeout(300)
        def verify_case():
            return verify_single_case(inputs_for_framework, inputs_for_impl)
        
        try:
            verify_result, framework_output = verify_case()
            if success_msg:
                print(success_msg)
            return verify_result, framework_output
        except TimeoutError:
            error_msg = timeout_msg or f"验证超时（300秒）"
            raise AssertionError(error_msg)

    # 获取初始化参数和输入数据
    init_params = get_init_inputs()
    
    # 设置随机种子以确保framework_model和impl_model的权重一致
    
    torch.manual_seed(0)
    
    
    framework_model = FrameworkModel(*init_params)
    
    
    framework_model = framework_model.to(device)
    
    
    # 创建 impl_model（用于 ModelNew 类格式的 DSL）
    
    impl_model = ModelNew(*init_params)
    
    impl_model = impl_model.to(device)
    
    
    
    # 静态shape：获取单组输入数据
    # 设置随机种子以确保数据可复现（先准备impl输入）
    
    torch.manual_seed(0)
    
    inputs_for_impl = get_inputs()
    
    inputs_for_impl = [process_input(x) for x in inputs_for_impl]
    
    
    # 重新生成输入数据用于framework（避免原地操作影响）
    
    torch.manual_seed(0)
    
    inputs_for_framework = get_inputs()
    
    inputs_for_framework = [process_input(x) for x in inputs_for_framework]
    
    
    # 使用带超时控制的验证函数
    verify_result, framework_output = verify_with_timeout(
        inputs_for_framework,
        inputs_for_impl,
        timeout_msg=f"静态shape验证超时（300秒）"
    )
    
    
    # 构建验证成功信息
    import time
    import uuid
    
    # 生成唯一标识符，避免并发时的日志混乱
    verification_id = str(uuid.uuid4())[:8]
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
    
    # 收集验证的基础信息
    verification_info = {
        "verification_id": verification_id,
        "timestamp": timestamp,
        "op_name": "matmul_transeposed_both",
        "framework": "torch",
        "backend": "cuda",
        "arch": "a100",
        "dsl": "triton_cuda",
        "device_id": 0,
        "status": "成功"
    }
    
    # 收集验证信息
    
    output_shapes = [str(out.shape) if hasattr(out, 'shape') else str(type(out)) for out in framework_output]
    output_dtypes = [str(out.dtype) if hasattr(out, 'dtype') else str(type(out)) for out in framework_output]
    verification_info.update({
        "shape_type": "static",
        "output_count": len(output_shapes),
        "output_shapes": output_shapes,
        "output_dtypes": output_dtypes
    })
    shape_info = f"形状类型: 静态 | 输出数量: {len(output_shapes)} | 形状: {output_shapes} | 数据类型: {output_dtypes}"
    
    
    # 格式化输出，确保并发时不会混乱
    verification_log = f"""[{verification_id}] 验证结果: 成功
[{verification_id}] 算子: matmul_transeposed_both | 框架: torch | 后端: cuda | 架构: a100
[{verification_id}] DSL: triton_cuda | 设备ID: 0 | 时间: {timestamp}
[{verification_id}] {shape_info}
[{verification_id}] {'='*60}\n\n"""
    
    print(verification_log)


if __name__ == "__main__":
    verify_implementations()
